### ISSUE TITLE
Wine text layout

### ISSUE THREAD

**Issue by TheresaRutledge** [TheresaRutledge/wine-and-dine#18]
-populates with text passed back from spoonacular call
-if no wine pairings were provided, has default message

**Comment by osbornroxas02** [comment]
* Redesigned wine cards 
* Added a text section

I redesigned it to be more similar to Mukuls image sections from our previous meeting. I simplified the cards and just made it responsive. Click on in and it enlarges.

* Added two text headers columns. An <h1> and <p> We need to pick which version we want.

* I add a CSS change to lightly grey out the background to make the section come out more. Purely optional.

**Comment by osbornroxas02** [comment]
continue..

H1 and P. We need to pick which version we want.

I add a CSS change to lightly grey out the background to make the section come out more. Purely optional.
