### ISSUE TITLE
Wine Cards

### ISSUE THREAD

**Issue by TheresaRutledge** [TheresaRutledge/wine-and-dine#3]
-area for img, title, description (img to come later)
-these will be created dynamically later

**Comment by osbornroxas02** [comment]
I create 2 versions of the Wine Card Section for us to choose from.
The first is ok but wont work so well with photo images of different sizes. We need to use our own images to make this work.
I prefer the second more. Its cleaner. Has better UX/UI features and is more adaptable. I still need to finish the section title

**Comment by osbornroxas02** [comment]
added a "Our top Choice" text option to the "Main Wine" Card item

**Comment by osbornroxas02** [comment]
updated draft is pending for review
